/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qarisiqmallar.veneramarket;

import com.mycompany.DaoInter.MehsullarDaoInter;
import com.mycompany.entity.Mehsullar;
import com.mycompany.main.Contex;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;
import org.apache.fontbox.ttf.BufferedRandomAccessFile;

/**
 *
 * @author Shamil
 */
public class AlisQaimeleri extends javax.swing.JFrame {

    protected String tamAd;

    public MehsullarDaoInter mehDao = Contex.instanceOfMehsullarDao();

    /**
     * Creates new form AlisQaimeleri
     */
    public AlisQaimeleri() throws Exception {
        initComponents();
        setScreenSize();
        connect();
        qaimelerinGetirilmesi();
        buttonGroup1.add(rbBugun);
        buttonGroup1.add(rbDunen);
        buttonGroup1.add(rbSonBirHefte);
        buttonGroup1.add(rbSonBirAy);

    }

    public void secilenTarixler() {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        Calendar cal = new GregorianCalendar();
//        cal.add(Calendar.DAY_OF_MONTH, -30);
//        String sss = sdf.format(cal.getTime());

        Date birinciTarix = ilkTarix.getDate();
        Date ikinciTarix = sonTarix.getDate();
        String sss = sdf.format(ilkTarix.getDate());
        String sss2 = sdf.format(sonTarix.getDate());

        System.out.println(sss);
        System.out.println(sss2);

        txtCemMebleg.removeAll();
        // System.out.println(sss);
        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri a where (a.Tarix) BETWEEN" + "'" + sss + "'" + "and" + "'" + sss2 + "'");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getInt("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }
        qaimelerinHesablanmasi();
    }

    public void setScreenSize() {

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    public void connect() throws Exception {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection("jdbc:mysql://localhost/mehsullar", "root", "dxdiag92");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQaimeler = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rbBugun = new javax.swing.JRadioButton();
        rbDunen = new javax.swing.JRadioButton();
        rbSonBirHefte = new javax.swing.JRadioButton();
        rbSonBirAy = new javax.swing.JRadioButton();
        ilkTarix = new com.toedter.calendar.JDateChooser();
        sonTarix = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        btnTemizle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCemMebleg = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        tblQaimeler.setBackground(new java.awt.Color(0, 153, 204));
        tblQaimeler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblQaimeler.setForeground(new java.awt.Color(255, 255, 255));
        tblQaimeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Kimden", "Qurum/Firma", "Qaime Nomresi", "Qaime Meblegi", "Tarix", "Status", "Kim terefinden", "Yenilenme Tarixi"
            }
        ));
        tblQaimeler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQaimelerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblQaimelerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblQaimelerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblQaimelerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblQaimelerMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblQaimeler);
        if (tblQaimeler.getColumnModel().getColumnCount() > 0) {
            tblQaimeler.getColumnModel().getColumn(0).setMinWidth(1);
            tblQaimeler.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblQaimeler.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        rbBugun.setText("Bugun");
        rbBugun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBugunActionPerformed(evt);
            }
        });

        rbDunen.setText("Dunen");
        rbDunen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDunenActionPerformed(evt);
            }
        });

        rbSonBirHefte.setText("Son 1 hefte");
        rbSonBirHefte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSonBirHefteActionPerformed(evt);
            }
        });

        rbSonBirAy.setText("Son 1 ay");
        rbSonBirAy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSonBirAyActionPerformed(evt);
            }
        });

        sonTarix.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                sonTarixInputMethodTextChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tarix sec..");

        jLabel2.setText("-qeder");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("-den");

        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate1.setIcon(new javax.swing.ImageIcon("C:\\GitHubProject\\VeneraMarket\\VeneraMarket\\VeneraMarket\\src\\main\\java\\pictures\\Button-Refresh-icon.png")); // NOI18N
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnTemizle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTemizle.setText("Temizle");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDunen)
                    .addComponent(rbBugun))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbSonBirHefte)
                                .addGap(18, 18, 18)
                                .addComponent(ilkTarix, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbSonBirAy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sonTarix, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTemizle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBugun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbSonBirHefte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSonBirAy)
                            .addComponent(rbDunen)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ilkTarix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sonTarix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCemMebleg.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCemMebleg.setForeground(new java.awt.Color(51, 51, 51));
        txtCemMebleg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\GitHubProject\\VeneraMarket\\VeneraMarket\\VeneraMarket\\src\\main\\java\\pictures\\Button-Refresh-icon.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1229, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCemMebleg, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCemMebleg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQaimelerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQaimelerMouseClicked

        try {
            try {
                df = (DefaultTableModel) tblQaimeler.getModel();

                int selected = tblQaimeler.getSelectedRow();

                String qaimeYolu = "C:\\Alis Qaimeleri\\";
                String qaimeAdi = (df.getValueAt(selected, 1).toString());
                String qurum = (df.getValueAt(selected, 2).toString());
                String qaimeNum = (df.getValueAt(selected, 3).toString());
                tamAd = qaimeAdi + "-" + qaimeNum + ".txt";

                pres = con.prepareStatement("truncate table qaimeyolu;");
                pres.executeUpdate();

                pres = con.prepareStatement("insert into qaimeyolu (QaimeAdi, QaimeYolu, Qurum, QaimeNum, Kimden) values(?,?,?,?,?)");
                pres.setString(1, tamAd);
                pres.setString(2, qaimeYolu);
                pres.setString(3, qurum);
                pres.setString(4, qaimeNum);
                pres.setString(5, qaimeAdi);
                pres.executeUpdate();

                //Mehsullar mm = mehDao.getProductByBillingNum(billingNum);
                //readBillFromFile();
                AlisQaimesiMehsullar ss = new AlisQaimesiMehsullar();

                ss.path = tamAd;

                ss.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(AlisQaimeleri.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            Logger.getLogger(AlisQaimeleri.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tblQaimelerMouseClicked


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblQaimelerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQaimelerMouseEntered


    }//GEN-LAST:event_tblQaimelerMouseEntered

    private void tblQaimelerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQaimelerMouseExited


    }//GEN-LAST:event_tblQaimelerMouseExited

    private void tblQaimelerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQaimelerMousePressed


    }//GEN-LAST:event_tblQaimelerMousePressed

    private void tblQaimelerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQaimelerMouseReleased


    }//GEN-LAST:event_tblQaimelerMouseReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        qaimelerinGetirilmesi();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void rbDunenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDunenActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = new GregorianCalendar();
        String ss = sdf.format(cal.getTime());
        cal.add(Calendar.DAY_OF_MONTH, -1);

        String sss = sdf.format(cal.getTime());

        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri a where Date (a.Tarix) = " + "'" + sss + "'");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getInt("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }
        qaimelerinHesablanmasi();

    }//GEN-LAST:event_rbDunenActionPerformed

    private void rbBugunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBugunActionPerformed

        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri a where Date (a.Tarix) = CURRENT_DATE");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getString("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }

        qaimelerinHesablanmasi();


    }//GEN-LAST:event_rbBugunActionPerformed

    public void allBills() {

        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getInt("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }

        

    }


    private void rbSonBirHefteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSonBirHefteActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = new GregorianCalendar();
        String ss = sdf.format(cal.getTime());
        cal.add(Calendar.DAY_OF_MONTH, -6);

        String sss = sdf.format(cal.getTime());

        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri a where (a.Tarix) BETWEEN" + "'" + sss + "'" + "and CURRENT_DATE");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getString("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }
        qaimelerinHesablanmasi();

    }//GEN-LAST:event_rbSonBirHefteActionPerformed

    private void rbSonBirAyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSonBirAyActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = new GregorianCalendar();
        String ss = sdf.format(cal.getTime());
        cal.add(Calendar.DAY_OF_MONTH, -31);

        String sss = sdf.format(cal.getTime());

        int a;
        try {

            pres = con.prepareCall("SELECT * FROM alisqaimeleri a where (a.Tarix) BETWEEN" + "'" + sss + "'" + "and CURRENT_DATE");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getString("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();

        }

    }//GEN-LAST:event_rbSonBirAyActionPerformed

    private void sonTarixInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sonTarixInputMethodTextChanged
        secilenTarixler();
    }//GEN-LAST:event_sonTarixInputMethodTextChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        secilenTarixler();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed

        Date ilktarix = ilkTarix.getDate();
        Date sontarix = sonTarix.getDate();
        if (ilktarix != null) {

        }

//        boolean yoxla = rbBugun.isSelected();
//        boolean yoxla2 = rbDunen.isSelected();
//        boolean yoxla3 = rbSonBirHefte.isSelected();
//        boolean yoxla4 = rbSonBirAy.isSelected();
        ButtonModel mm = buttonGroup1.getSelection();

        if (mm != null) {
            buttonGroup1.clearSelection();
        }

       allBills();
       qaimelerinHesablanmasi();

    }//GEN-LAST:event_btnTemizleActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
       
        qaimelerinGetirilmesi();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlisQaimeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlisQaimeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlisQaimeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlisQaimeleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlisQaimeleri().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AlisQaimeleri.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    Connection con;
    PreparedStatement pres;
    Statement stmt;
    DefaultTableModel df;

    public void qaimelerinGetirilmesi() {

        DecimalFormat dformater = new DecimalFormat("#.##");

        int a;
        try {
            pres = con.prepareCall("select * from alisqaimeleri");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblQaimeler.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Kimden"));
                    v2.add(rs.getString("Qurum"));
                    v2.add(rs.getString("QaimeNomresi"));
                    v2.add(rs.getDouble("QaimeMeblegi"));
                    v2.add(rs.getString("Tarix"));
                    v2.add(rs.getString("Status"));
                    v2.add(rs.getString("KimTerefinden"));
                    v2.add(rs.getString("YenilenmeTarixi"));

                }
                df.addRow(v2);

            }

            df = (DefaultTableModel) tblQaimeler.getModel();

            double toplam, cem = 0;

            for (int i = 0; i < df.getRowCount(); i++) {

                toplam = Double.parseDouble(df.getValueAt(i, 4).toString());
                cem += toplam;
                String formattedGelir = dformater.format(cem);
                txtCemMebleg.setText(formattedGelir);

            }

        } catch (SQLException ex) {

            ex.printStackTrace();

        }

    }

    public void qaimelerinHesablanmasi() {
        DecimalFormat dformater = new DecimalFormat("#.##");

        df = (DefaultTableModel) tblQaimeler.getModel();

        double toplam, cem = 0;

        for (int i = 0; i < df.getRowCount(); i++) {

            toplam = Double.parseDouble(df.getValueAt(i, 4).toString());
            cem += toplam;
            String formattedGelir = dformater.format(cem);
            txtCemMebleg.setText(formattedGelir);

        }

    }

    public void readBillFromFile() {

        String pathName = "C:\\burayaz\\test.txt";

        File file = new File(pathName);

        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            df = (DefaultTableModel) tblQaimeler.getModel();
            Object[] lines = br.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                df.addRow(row);

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AlisQaimeleri.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTemizle;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser ilkTarix;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbBugun;
    private javax.swing.JRadioButton rbDunen;
    private javax.swing.JRadioButton rbSonBirAy;
    private javax.swing.JRadioButton rbSonBirHefte;
    private com.toedter.calendar.JDateChooser sonTarix;
    private javax.swing.JTable tblQaimeler;
    private javax.swing.JTextField txtCemMebleg;
    // End of variables declaration//GEN-END:variables
}
