/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qarisiqmallar.veneramarket;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shamil
 */
public class BorclarDetalli extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pres;
    DefaultTableModel df;

    public BorclarDetalli() {
        initComponents();
        connect();
        dettaliBax();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBorclularSiyahisi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBorclularSiyahisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Borclunun adi", "Mehsul", "Miqdari", "Qiymeti", "Umumi mebleğ", "Qismen Ödeniş", "Qalıq Borc"
            }
        ));
        jScrollPane1.setViewportView(tblBorclularSiyahisi);
        if (tblBorclularSiyahisi.getColumnModel().getColumnCount() > 0) {
            tblBorclularSiyahisi.getColumnModel().getColumn(0).setMinWidth(30);
            tblBorclularSiyahisi.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblBorclularSiyahisi.getColumnModel().getColumn(0).setMaxWidth(100);
            tblBorclularSiyahisi.getColumnModel().getColumn(1).setMinWidth(50);
            tblBorclularSiyahisi.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblBorclularSiyahisi.getColumnModel().getColumn(1).setMaxWidth(200);
            tblBorclularSiyahisi.getColumnModel().getColumn(3).setMinWidth(30);
            tblBorclularSiyahisi.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblBorclularSiyahisi.getColumnModel().getColumn(3).setMaxWidth(100);
            tblBorclularSiyahisi.getColumnModel().getColumn(4).setMinWidth(30);
            tblBorclularSiyahisi.getColumnModel().getColumn(4).setPreferredWidth(55);
            tblBorclularSiyahisi.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorclarDetalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorclarDetalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorclarDetalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorclarDetalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorclarDetalli().setVisible(true);
            }
        });
    }

    public void connect() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/mehsullar", "root", "dxdiag92");
            } catch (SQLException ex) {
                Logger.getLogger(BorclarDetalli.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BorclarDetalli.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void dettaliBax() {
        int id = 0;
        int a;
        try {

            pres = con.prepareCall("select * from detallar");
            ResultSet rs = pres.executeQuery();

            while (rs.next()) {

                id = rs.getInt("id");

            }

            pres = con.prepareCall("SELECT\n"
                    + "	b.Mehsul_ID,\n"
                    + "	b.Borc_alanin_adi,\n"
                    + "	b.Borca_goturduyu_mehsul,\n"
                    + "	b.Miqdari,\n"
                    + "	b.Qiymeti,\n"
                    + "	b.Umumi_mebleg,\n"
                    + "	b.Qismen_odenis,\n"
                    + "	b.Qaliq_borc\n"
                    + "FROM\n"
                    + "	borclar_siyahisi b\n"
                    + "	LEFT JOIN mehsullar m on m.id = b.Mehsul_ID where m.id = " + id);
            ResultSet rss = pres.executeQuery();

            ResultSetMetaData rd = rss.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblBorclularSiyahisi.getModel();
            df.setRowCount(0);

            while (rss.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rss.getInt("Mehsul_ID"));
                    v2.add(rss.getString("Borc_alanin_adi"));
                    v2.add(rss.getString("Borca_goturduyu_mehsul"));
                    v2.add(rss.getInt("Miqdari"));
                    v2.add(rss.getDouble("Qiymeti"));
                    v2.add(rss.getDouble("Umumi_mebleg"));
                    v2.add(rss.getDouble("Qismen_odenis"));
                    v2.add(rss.getDouble("Qaliq_borc"));
                }
                df.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(exploreAboutProduct.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBorclularSiyahisi;
    // End of variables declaration//GEN-END:variables
}
