/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.qarisiqmallar.veneramarket;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Shamil
 */
public class CreateNewClient extends javax.swing.JDialog {

    Connection con;
    PreparedStatement pres;
    ResultSet rs;

    /**
     * Creates new form CreateNewClient
     *
     * @param parent
     * @param modal
     */
    public CreateNewClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNameAndSurename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtphoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemailAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtNumberOfDebtCard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnumberOfContract = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        percentageOfSalePrice = new javax.swing.JTextField();
        cbOption = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ad ve Soyad :");

        txtNameAndSurename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameAndSurenameFocusLost(evt);
            }
        });
        txtNameAndSurename.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtNameAndSurenameMouseWheelMoved(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Yeni müşterinin melumatları..");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Debet kart seria nömresi (16 reqemli) :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Telefon nömresi :");

        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Elektron poçt ünvanı :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Müqavle nömresi :");

        txtnumberOfContract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnumberOfContractMouseClicked(evt);
            }
        });
        txtnumberOfContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberOfContractActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Müqavile qiymeti  :");

        percentageOfSalePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                percentageOfSalePriceKeyPressed(evt);
            }
        });

        cbOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "%", "рубл" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNameAndSurename, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnumberOfContract, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtemailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumberOfDebtCard, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(percentageOfSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(19, 19, 19)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameAndSurename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumberOfContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberOfDebtCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageOfSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection connect() {
        try {

            //Class.forName("com.mysql.jdbc.Driver");
            String url = ("jdbc:mysql://localhost:3306/mehsullar");
            String usercategoryOfProduct = ("root");
            String password = ("dxdiag92");
            con = DriverManager.getConnection(url, usercategoryOfProduct, password);

        } catch (Exception ex) {

        }

        return con;

    }


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        Ok();

    }//GEN-LAST:event_btnSaveActionPerformed

    public void Ok() {

        String numberOfDebtCard = txtNumberOfDebtCard.getText();
        String emailAddress = txtemailAddress.getText();
        String phoneNumber = txtphoneNumber.getText();
        String numberOfContract = txtnumberOfContract.getText();
        String NameAndSurename = txtNameAndSurename.getText();
        double txtPercentageOfSalePrice = Double.parseDouble(percentageOfSalePrice.getText());
        String option = cbOption.getSelectedItem().toString();

        if (NameAndSurename.isEmpty() == true) {

            JOptionPane.showMessageDialog(this, "Пожалуйста, заполните информацию полностью");

        } else {

            try {
                con = connect();
                pres = con.prepareStatement("insert into clients (NameAndSurename, NumberOfContract, PhoneNumber, EmailAddress, NumberOfDebetCard, PersentageOfSalePrice, OptionOnRubleAndPercentage) values (?,?,?,?,?,?,?)");
                pres.setString(1, NameAndSurename);
                pres.setString(2, numberOfContract);
                pres.setString(3, phoneNumber);
                pres.setString(4, emailAddress);
                pres.setString(5, numberOfDebtCard);
                pres.setDouble(6, txtPercentageOfSalePrice);
                pres.setString(7, option);
                pres.executeUpdate();

                //Клиент по имени Samil успешно создан
                JOptionPane.showMessageDialog(this, NameAndSurename + " - adli müşteri uğurla qeyd ulundu!");

                txtNumberOfDebtCard.setText("");
                txtemailAddress.setText("");
                txtphoneNumber.setText("");
                txtnumberOfContract.setText("");
                txtNameAndSurename.setText("");
                percentageOfSalePrice.setText("");

            } catch (Exception ex) {

                ex.printStackTrace();
            }

        }

    }

    private void txtnumberOfContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberOfContractActionPerformed


    }//GEN-LAST:event_txtnumberOfContractActionPerformed
    SimpleDateFormat sdf = new SimpleDateFormat();
    Date dt = new Date();
    SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy");
    String time = sdf2.format(dt);


    private void txtnumberOfContractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnumberOfContractMouseClicked

        int i = checkCurrentClientName2();

        if (i > 0) {

        } else {

            String name = txtNameAndSurename.getText();
            String randomCode = RandomCodeGenerator.randomCodeGenerate();
            txtnumberOfContract.setText(time + "-" + randomCode + "-" + name.substring(0, 3));

        }


    }//GEN-LAST:event_txtnumberOfContractMouseClicked

    private void percentageOfSalePriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentageOfSalePriceKeyPressed

        int s = evt.getKeyCode();
        if (s == 10) {
            Ok();
        }
    }//GEN-LAST:event_percentageOfSalePriceKeyPressed

    private void txtNameAndSurenameMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtNameAndSurenameMouseWheelMoved

        checkCurrentClientName();

    }//GEN-LAST:event_txtNameAndSurenameMouseWheelMoved

    private void txtNameAndSurenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameAndSurenameFocusLost
        checkCurrentClientName();
    }//GEN-LAST:event_txtNameAndSurenameFocusLost

    public int checkCurrentClientName() {
        int i = 0;
        String currentClientName = txtNameAndSurename.getText();

        try {

            con = connect();
            pres = con.prepareStatement("select * from clients where NameAndSurename = " + "'" + currentClientName + "'");
            rs = pres.executeQuery();

            if (rs.next()) {

                JOptionPane.showMessageDialog(this, currentClientName + "-adli musteri artiq movcuddur!", "Diqqet!", HEIGHT);
                btnSave.disable();
                cbOption.disable();
                percentageOfSalePrice.disable();
                txtNumberOfDebtCard.disable();
                txtemailAddress.disable();
                txtphoneNumber.disable();
                txtnumberOfContract.disable();
                i++;

            } else {

                 btnSave.enable();
                cbOption.enable();
                percentageOfSalePrice.enable();
                txtNumberOfDebtCard.enable();
                txtemailAddress.enable();
                txtphoneNumber.enable();
                txtnumberOfContract.enable();

            }

        } catch (Exception ex) {

            ex.printStackTrace();

        }
        return i;
    }

    
    public int checkCurrentClientName2() {
        int i = 0;
        String currentClientName = txtNameAndSurename.getText();

        try {

            con = connect();
            pres = con.prepareStatement("select * from clients where NameAndSurename = " + "'" + currentClientName + "'");
            rs = pres.executeQuery();

            if (rs.next()) {

                
                btnSave.disable();
                cbOption.disable();
                percentageOfSalePrice.disable();
                txtNumberOfDebtCard.disable();
                txtemailAddress.disable();
                txtphoneNumber.disable();
                txtnumberOfContract.disable();
                i++;

            } else {

                 btnSave.enable();
                cbOption.enable();
                percentageOfSalePrice.enable();
                txtNumberOfDebtCard.enable();
                txtemailAddress.enable();
                txtphoneNumber.enable();
                txtnumberOfContract.enable();

            }

        } catch (Exception ex) {

            ex.printStackTrace();

        }
        return i;
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateNewClient dialog = new CreateNewClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField percentageOfSalePrice;
    private javax.swing.JTextField txtNameAndSurename;
    private javax.swing.JTextField txtNumberOfDebtCard;
    private javax.swing.JTextField txtemailAddress;
    private javax.swing.JTextField txtnumberOfContract;
    private javax.swing.JTextField txtphoneNumber;
    // End of variables declaration//GEN-END:variables
}
