/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qarisiqmallar.veneramarket;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shamil
 */
public class ExistingProductsAcilanQaime extends javax.swing.JFrame {

    int clickedId;

    Date date = new Date();
    Calendar calendar;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd ");
    String date2 = sdf.format(date);

    public ExistingProductsAcilanQaime() throws Exception {
        initComponents();

        connect();
        load();
        txtTarix.setText(date2);
        setScreenSize();

    }

    Connection con;
    PreparedStatement pres;
    DefaultTableModel df;

    public void connect() throws Exception {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection("jdbc:mysql://localhost/mehsullar", "root", "dxdiag92");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblexistProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAxtaris = new javax.swing.JTextField();
        cbSecim = new javax.swing.JComboBox<>();
        txtAdd = new javax.swing.JTextField();
        txtMalinAdi = new javax.swing.JTextField();
        txtFaktikMebleg = new javax.swing.JTextField();
        txtFaktikSay = new javax.swing.JTextField();
        txtSatisQiymeti = new javax.swing.JTextField();
        txtAlisQiymeti = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtYeniAlinancem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTarix = new javax.swing.JTextField();
        txtAlisTarixi = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblexistProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Mehsulun Adi", "Miqdari", "Satis Miqdari", "Qaliq Say", "Alis Qiymeti", "Satis Qiymeti", "Umumi Mebleg", "Tarix ", "Barcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblexistProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblexistProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblexistProduct);
        if (tblexistProduct.getColumnModel().getColumnCount() > 0) {
            tblexistProduct.getColumnModel().getColumn(0).setMinWidth(1);
            tblexistProduct.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblexistProduct.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Axtar..");

        txtAxtaris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAxtarisKeyReleased(evt);
            }
        });

        cbSecim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbSecim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada göre", "Barkoda göre" }));
        cbSecim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSecimActionPerformed(evt);
            }
        });

        txtAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });
        txtAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddKeyTyped(evt);
            }
        });

        txtMalinAdi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMalinAdi.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFaktikMebleg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFaktikMebleg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFaktikSay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFaktikSay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSatisQiymeti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSatisQiymeti.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlisQiymeti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlisQiymeti.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtYeniAlinancem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtYeniAlinancem.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mehsulun Adi :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Elave olunan miqdar :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Satış qiymeti :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Alış qiymeti :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Yeni Cem Mebleğ :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Faktik Miqdar :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ümumi Cem :");

        txtTarix.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTarix.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlisTarixi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlisTarixi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtAlisTarixi.setText("Tarix :");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Bağla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtAlisTarixi, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFaktikSay, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFaktikMebleg, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMalinAdi)
                        .addComponent(txtSatisQiymeti, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAlisQiymeti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(txtYeniAlinancem, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTarix, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSecim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtAxtaris, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMalinAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlisQiymeti, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSatisQiymeti, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYeniAlinancem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaktikSay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaktikMebleg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTarix, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlisTarixi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAxtaris)
                    .addComponent(cbSecim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSecimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSecimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSecimActionPerformed

    private void txtAxtarisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAxtarisKeyReleased

        axtaris();


    }//GEN-LAST:event_txtAxtarisKeyReleased

    private void tblexistProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblexistProductMouseClicked

        mouseClicked();
    }//GEN-LAST:event_tblexistProductMouseClicked

    private void txtAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyReleased


    }//GEN-LAST:event_txtAddKeyReleased

    private void txtAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyTyped

    }//GEN-LAST:event_txtAddKeyTyped

    private void txtAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyPressed


    }//GEN-LAST:event_txtAddKeyPressed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        DecimalFormat dformater = new DecimalFormat("#.##");

        double faktikSay = Double.parseDouble(txtFaktikSay.getText());
        int add = Integer.parseInt(txtAdd.getText());
        double faktik = Double.parseDouble(txtFaktikSay.getText());
        double alisqiymeti = Double.parseDouble(txtAlisQiymeti.getText());
        double kohneUmumiAlisMeb = Double.parseDouble(txtFaktikMebleg.getText());

        double yeniFaktikSay = add + faktik;
        double umumiAlisMeblegi = kohneUmumiAlisMeb + add * alisqiymeti;
        double yeniAlinanCemMebleg = add * alisqiymeti;

        txtFaktikMebleg.setText(Double.toString(umumiAlisMeblegi));
        txtFaktikSay.setText(Double.toString(yeniFaktikSay));
        txtYeniAlinancem.setText(Double.toString(yeniAlinanCemMebleg));


    }//GEN-LAST:event_txtAddActionPerformed

    public void setScreenSize() {

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addExistProductToTheNewList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);

        AlisQaimesi geriQayitmaq;
        try {
            geriQayitmaq = new AlisQaimesi();
            geriQayitmaq.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ExistingProductsAcilanQaime().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void addExistProductToTheNewList() {

        df = (DefaultTableModel) tblexistProduct.getModel();

        int selected = tblexistProduct.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        String malinAdi = txtMalinAdi.getText();
        int miqdari = Integer.parseInt(txtAdd.getText());
        int satisMiqdari = Integer.parseInt(df.getValueAt(selected, 3).toString());
        int faktikSay = Integer.parseInt(txtFaktikSay.getText());

        double alisQiymeti = Double.parseDouble(txtAlisQiymeti.getText());
        double satisQiymeti = Double.parseDouble(txtSatisQiymeti.getText());
        String tarix = txtTarix.getText();
        double umumiMebleg = Double.parseDouble(txtFaktikMebleg.getText());
        double yeniAlinanCemMebleg = Double.parseDouble(txtYeniAlinancem.getText());
        String barcode = df.getValueAt(selected, 9).toString();
        String status = "updated";
        try {
            pres = con.prepareStatement("insert into acilanqaime ( id, Malin_adi, Miqdari, Alis_qiymeti, Satis_Miqdari, Satis_qiymeti, Qaliq_say, Alis_Tarixi, Alisin_toplam_deyer, Barcode, Status, CariAlisMeblegi ) values(?,?,?,?,?,?,?,?,?,?,?,?)");

            pres.setInt(1, id);
            pres.setString(2, malinAdi);
            pres.setInt(3, miqdari);
            pres.setDouble(4, alisQiymeti);
            pres.setInt(5, satisMiqdari);
            pres.setDouble(6, satisQiymeti);
            pres.setInt(7, faktikSay);
            pres.setString(8, tarix);
            pres.setDouble(9, umumiMebleg);
            pres.setString(10, barcode);
            pres.setString(11, status);
            pres.setDouble(12, yeniAlinanCemMebleg);
            pres.executeUpdate();
            JOptionPane.showMessageDialog(this, "Mehsul elave olundu");

            try {
                AlisQaimesiMehsullar geriQayitmaq = new AlisQaimesiMehsullar();

                geriQayitmaq.isFocusableWindow();

                geriQayitmaq.setVisible(false);
                geriQayitmaq.setVisible(true);

                this.setVisible(false);

            } catch (Exception ex) {
                Logger.getLogger(ExistingProductsAcilanQaime.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Satici_Elave_Etmek.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void load() {

        int a;
        try {
            pres = con.prepareCall("select * from mehsullar");

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblexistProduct.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {

                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Malin_adi"));
                    v2.add(rs.getInt("Miqdari"));
                    v2.add(rs.getInt("Satis_miqdari"));
                    v2.add(rs.getInt("Qaliq_say"));
                    v2.add(rs.getDouble("Alis_qiymeti"));
                    v2.add(rs.getDouble("Satis_qiymeti"));
                    v2.add(rs.getDouble("Alisin_toplam_deyer"));
                    v2.add(rs.getString("Alis_Tarixi"));
                    v2.add(rs.getString("Barcode"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            Logger.getLogger(Satici_Elave_Etmek.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void mouseClicked() {

        df = (DefaultTableModel) tblexistProduct.getModel();

        int selected = tblexistProduct.getSelectedRow();

        clickedId = Integer.parseInt(df.getValueAt(selected, 0).toString());
        String malinadi = (df.getValueAt(selected, 1).toString());
        int miqdari = Integer.parseInt(df.getValueAt(selected, 2).toString());
        int satisMiqdari = Integer.parseInt(df.getValueAt(selected, 3).toString());
        double qaliqSay = Double.parseDouble(df.getValueAt(selected, 4).toString());
        double alisQiymeti = Double.parseDouble(df.getValueAt(selected, 5).toString());
        double satisQiymeti = Double.parseDouble(df.getValueAt(selected, 6).toString());
        double umumiMebleg = Double.parseDouble(df.getValueAt(selected, 7).toString());
        String tarix = (df.getValueAt(selected, 8).toString());
        String barcode = (df.getValueAt(selected, 9).toString());

        txtMalinAdi.setText(df.getValueAt(selected, 1).toString());
        txtFaktikSay.setText(df.getValueAt(selected, 4).toString());
        txtAlisQiymeti.setText(df.getValueAt(selected, 5).toString());
        txtSatisQiymeti.setText(df.getValueAt(selected, 6).toString());
        txtFaktikMebleg.setText(df.getValueAt(selected, 7).toString());       

        txtAdd.setText("");
        txtAdd.requestFocus();
        txtYeniAlinancem.setText("");


    }

    public void axtaris() {

        int typeOfSerach = cbSecim.getSelectedIndex();

        String s = txtAxtaris.getText();

        int a;
        try {

            if (typeOfSerach == 0) {
                pres = con.prepareCall("select * from mehsullar m where m.Malin_adi like " + "'" + "%" + s + "%" + "'");
            } else {
                pres = con.prepareCall("select * from mehsullar m where m.Barcode like " + "'" + "%" + s + "%" + "'");

            }

            ResultSet rs = pres.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) tblexistProduct.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < a; i++) {
                    v2.add(rs.getInt("id"));
                    v2.add(rs.getString("Malin_adi"));
                    v2.add(rs.getInt("Miqdari"));
                    v2.add(rs.getInt("Satis_miqdari"));
                    v2.add(rs.getDouble("Qaliq_say"));
                    v2.add(rs.getDouble("Alis_qiymeti"));
                    v2.add(rs.getDouble("Satis_qiymeti"));
                    v2.add(rs.getDouble("Alisin_toplam_deyer"));
                    v2.add(rs.getString("Alis_Tarixi"));
                    v2.add(rs.getString("Barcode"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            Logger.getLogger(Satici_Elave_Etmek.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSecim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblexistProduct;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAlisQiymeti;
    private javax.swing.JLabel txtAlisTarixi;
    private javax.swing.JTextField txtAxtaris;
    private javax.swing.JTextField txtFaktikMebleg;
    private javax.swing.JTextField txtFaktikSay;
    private javax.swing.JTextField txtMalinAdi;
    private javax.swing.JTextField txtSatisQiymeti;
    private javax.swing.JTextField txtTarix;
    private javax.swing.JTextField txtYeniAlinancem;
    // End of variables declaration//GEN-END:variables
}
