/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qarisiqmallar.veneramarket;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shamil
 */
public class IdentificationOfProduuctBarcodes extends javax.swing.JFrame {

    DefaultTableModel df;
    Connection con;
    ResultSet rs;
    PreparedStatement pres;

    public IdentificationOfProduuctBarcodes() {
        initComponents();
    }

    public Connection connect() {
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            String url = ("jdbc:mysql://localhost:3306/mehsullar");
            String usercategoryOfProduct = ("root");
            String password = ("dxdiag92");
            con = DriverManager.getConnection(url, usercategoryOfProduct, password);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return con;

    }

    public void identificationBarcodes() {
        DefaultListModel modelList = new DefaultListModel();
        modelList.removeAllElements();

        df = (DefaultTableModel) tblFirstProductTable.getModel();

        String barcode = null;
        String barcode2 = null;
        String nameOfFirstProduct = null;
        String nameOfSecondProduct = null;
        try {
            con = connect();

            pres = con.prepareStatement("select s.Qaliq_say, s.id, s.Barcode, s.Malin_adi from mehsullar s");
            rs = pres.executeQuery();

            while (rs.next()) {

                int qaliqSay = rs.getInt("Qaliq_say");
                int idFirstProduct = rs.getInt("id");
                barcode = rs.getString("Barcode");
                nameOfFirstProduct = rs.getString("Malin_adi");

                if (barcode == null) {

                } else {

                    pres = con.prepareStatement("select * from mehsullar");
                    ResultSet rs2 = pres.executeQuery();

                    while (rs2.next()) {

                        int qaliqSay2 = rs2.getInt("Qaliq_say");
                        int idSecondProduct = rs2.getInt("id");
                        barcode2 = rs2.getString("Barcode");
                        nameOfSecondProduct = rs2.getString("Malin_adi");

                        if (barcode2 == null) {

                        } else {

                            if (barcode.equals(barcode2)) {

                                if (idFirstProduct != idSecondProduct) {

                                    modelList.addElement("adi -" + nameOfFirstProduct + " id-si " + idFirstProduct + " olan mehsul ve adi -" + nameOfSecondProduct + " id-si " + idSecondProduct + " olan mehsul ile eyni barkoda sahibdirler");
                                    listNameOfClients.setModel(modelList);
                                    System.out.println(nameOfFirstProduct + " id-si " + idFirstProduct + " ve " + nameOfSecondProduct + " id-si " + idSecondProduct + " eyni barkoda sahibdirler");

                                    int a;
                                    ResultSetMetaData rd = rs.getMetaData();
                                    a = rd.getColumnCount();
                                    df.setRowCount(0);
                                    Vector v2 = new Vector();
                                    for (int i = 0; i < 1; i++) {
                                        v2.add(nameOfFirstProduct);
                                        v2.add(idFirstProduct);
                                        v2.add(rs.getString("Barcode"));
                                        v2.add(rs.getInt("Qaliq_say"));

                                    }

                                    df.addRow(v2);

                                } else {

                                }

                            }

                        }

                    }

                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSecondProductTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFirstProductTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNameOfClients = new javax.swing.JList<>();
        txtNumberOfTheSameProduct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("Yeni barcode teyin et");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblSecondProductTable = new JTable()

        {
            public boolean isCellEditable(int row, int column)

            {
                for(int i =0; i< tblSecondProductTable.getRowCount(); i++)
                {
                    if(row == i)
                    {
                        return false;
                    }
                }
                return false;
            }
        };
        tblSecondProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mehsul adi", "ID", "Barcode", "Qaliq say"
            }
        ));
        tblSecondProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSecondProductTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSecondProductTable);

        tblFirstProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mehsul adi", "ID", "Barcode", "Qaliq say"
            }
        ));
        tblFirstProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblFirstProductTableMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblFirstProductTable);

        jScrollPane1.setViewportView(listNameOfClients);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtNumberOfTheSameProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Barkodu eyni olan mehsullarin sayi :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumberOfTheSameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtNumberOfTheSameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        TestClass test = new TestClass();
        test.identificationBarcodes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSecondProductTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSecondProductTableMouseReleased

        if (SwingUtilities.isRightMouseButton(evt)) {

            jPopupMenu1.show(tblSecondProductTable, evt.getX(), evt.getY());

        }


    }//GEN-LAST:event_tblSecondProductTableMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        int selectedRow = 0;
        int id = 0;
        String nameOfProduct = null;
        int qaliqSay = 0;
        double priceBuy = 0;
        double priceSale = 0;
        String barcode = null;

        df = (DefaultTableModel) tblSecondProductTable.getModel();
        selectedRow = tblSecondProductTable.getSelectedRow();

        if (selectedRow == (-1)) {
            
            df = (DefaultTableModel) tblFirstProductTable.getModel();
            selectedRow = tblFirstProductTable.getSelectedRow();

        }

        id = Integer.parseInt(df.getValueAt(selectedRow, 1).toString());
        barcode = df.getValueAt(selectedRow, 2).toString();

        EditBarcode edit = new EditBarcode(this, true);

        edit.txtBarcode.setText(barcode);

        edit.setVisible(true);

        String barcode2 = edit.getBarcode();

        try {

            con = connect();
            pres = con.prepareStatement("update mehsullar set Barcode=? where id = " + id);
            pres.setString(1, barcode2);
            pres.executeUpdate();

            JOptionPane.showMessageDialog(this, "Mehsul melumatlari ugurla yenilendi");

        } catch (Exception ex2) {

            ex2.printStackTrace();

        }

        TestClass test = new TestClass();
        test.identificationBarcodes();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblFirstProductTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFirstProductTableMouseReleased

        if (SwingUtilities.isRightMouseButton(evt)) {

            jPopupMenu1.show(tblFirstProductTable, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_tblFirstProductTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentificationOfProduuctBarcodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentificationOfProduuctBarcodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentificationOfProduuctBarcodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentificationOfProduuctBarcodes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdentificationOfProduuctBarcodes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JList<String> listNameOfClients;
    public static javax.swing.JTable tblFirstProductTable;
    public static javax.swing.JTable tblSecondProductTable;
    public static javax.swing.JTextField txtNumberOfTheSameProduct;
    // End of variables declaration//GEN-END:variables
}
